add error handeling

diff --git a/.github/workflows/detect_changes.yml b/.github/workflows/detect_changes.yml
--- a/.github/workflows/detect_changes.yml
+++ b/.github/workflows/detect_changes.yml
@@ -63,11 +63,15 @@ jobs:
             "description": $new_description
           }
         }')
-        curl -D- \
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
           -u ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
           -X PUT \
           --data "$JSON" \
           -H "Content-Type: application/json" \
-          https://eltakotestinstance.atlassian.net/rest/api/2/issue/${{ steps.find_issue_key.outputs.issue }}
+          https://eltakotestinstance.atlassian.net/rest/api/2/issue/${{ steps.find_issue_key.outputs.issue }})
+        if [ $RESPONSE -ne 200 ]; then
+          echo "Error: HTTP status code $RESPONSE"
+          exit 1
+        fi
     
 
