test custom field

diff --git a/.github/workflows/milestones_opened.yml b/.github/workflows/milestones_opened.yml
--- a/.github/workflows/milestones_opened.yml
+++ b/.github/workflows/milestones_opened.yml
@@ -33,26 +33,29 @@ jobs:
         issuetype: Epic
         summary: ${{ github.event.milestone.title }} 
         description: "in ${{ github.repository }} branch ${{ steps.extract_branch.outputs.branch }}\nDescription: ${{ github.event.milestone.description }}"
+        fields: '{"duedate": "${{ github.event.milestone.due_on }}",
+                  "fromGithub" :  "1"}'
+
         
-    - name: set Due date
-      run: |
-        JSON=$(jq -n \
-        --arg due_date "${{ github.event.milestone.due_on }}" \
-        '{
-          "fields": {
-            "duedate": $due_date
-          }
-        }')
-        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
-          -u ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
-          -X PUT \
-          --data "$JSON" \
-          -H "Content-Type: application/json" \
-          https://eltakotestinstance.atlassian.net/rest/api/2/issue/${{ steps.create.outputs.issue }})
-        if [ $RESPONSE -ne 204 ]; then
-          echo "Error: HTTP status code $RESPONSE"
-          exit 1
-        fi
+    #- name: set Due date
+    #  run: |
+    #    JSON=$(jq -n \
+    #    --arg due_date "${{ github.event.milestone.due_on }}" \
+    #    '{
+    #      "fields": {
+    #        "duedate": $due_date
+    #      }
+    #    }')
+    #    RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
+    #      -u ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
+    #      -X PUT \
+    #      --data "$JSON" \
+    #      -H "Content-Type: application/json" \
+    #      https://eltakotestinstance.atlassian.net/rest/api/2/issue/${{ steps.create.outputs.issue }})
+    #    if [ $RESPONSE -ne 204 ]; then
+    #      echo "Error: HTTP status code $RESPONSE"
+    #      exit 1
+    #    fi
         
     - name: Log created issue
       run: echo "Epic ${{ steps.create.outputs.issue }} was created"
